name: Daily Snack Notifier

on:
  schedule:
    # 4:00 PM to 5:00 PM IST is 10:30 AM to 11:30 AM UTC
    # This runs every 15 minutes during that hour
    - cron: '30,45,00,15 10,11 * * *'
  workflow_dispatch: # Allows you to run it manually to test

jobs:
  check-snacks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run Scraper
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
        run: python bot.py
